version: '3.8'

services:
  ssu-flask-app:
    image: ${DOCKER_USERNAME:-your-username}/ssu-flask-app:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped
